version: "3.9"
services:
  vintagestory:
    image: snook9/vintagestory_server:latest
    ports:
      - "42420:42420"
    restart: unless-stopped
    volumes:
      - /media/data/vintagestory:/var/vintagestory/data
